version: '3'
services:

  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nestjsbackend:latest
    container_name: nestjs-backend-container
    ports:
      - "3030:3030"
      - "8000:8000"
      - "1935:1935"
    volumes:
      - ./data:/app/data